### PR TITLE
Fix constraint message

### LINKED ISSUE #144: Wrong error messages for role, missing constraint for tag
Error is role name too long but error message doesn't reflect this.
Image
Tag has no limit on length, despite documentation stating otherwise.

### PR DESCRIPTION
**Pull request by yitao36**
Fixes #144

### CODE REVIEW

File: src/main/java/seedu/address/model/role/Role.java [hunk 1]
```diff
@@ -10,7 +10,9 @@
 public class Role {
     public static final int PERSON_MAX_ROLES = 3;
     public static final String PERSON_ROLES_SIZE_CONSTRAINT = "Each person can have a maximum of 3 roles!";
-    public static final String MESSAGE_CONSTRAINTS = "Role names should be alphanumeric with spaces.";
+    public static final String MESSAGE_CONSTRAINTS = "Role names should be alphanumeric with spaces, "
+            + "and each role is at max 20 characters long, "
+            + "and each person can have a maximum of 3 roles.";
     public static final String FIND_MESSAGE_CONSTRAINTS = "Supplied substrings for roles should be "
```
Comment (ngyupeng) [inline src/main/java/seedu/address/model/role/Role.java]: Should probably update the constraint here as well?

**Review by ngyupeng — CHANGES_REQUESTED** [review]
Looks good, just update the error message for find function also.

**Review by ngyupeng — APPROVED** [review]
LGTM!
